name: 🧪 ModuleFast Action Test
on:
  push:
  workflow_dispatch:
defaults:
  run:
    shell: pwsh
jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        release:
          - main
          - latest
          - v0.2.0
    name: 🧪 ModuleFast Action Test
    runs-on: ${{ matrix.os }}
    steps:
      - name: 📂 Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🧪 ModuleFast Action - Specification
        uses: ./
        with:
          release: ${{ matrix.release }}
          specification: |
            Az
            ImportExcel
            TeamViewerPS
            PendingReboot
      - name: 🧪 Verify ModuleFast Action - Specification
        run: |
          Get-Module -ListAvailable DellBIOSProvider -ErrorAction Stop

      - name: 🧪 ModuleFast Action - Requires File Detection
        uses: ./
        with:
          release: main
      - name: 🧪 Verify ModuleFast Action - Specification
        run: |
          Get-Module -ListAvailable Az.Accounts -ErrorAction Stop
